#!/usr/bin/env bash

# Check if Nix is installed
if ! command -v nix > /dev/null; then
  echo "Nix is not installed. Installing..."

  # Install Nix with experimental flake config
  sh <(curl -L https://nixos.org/nix/install) --yes --daemon 

  # Add Nix to PATH
  source /etc/profile.d/nix.sh
fi

echo "Nix is installed."

# Install Home
yes | nix run nixpkgs#home-manager -- switch --flake github:shikanime/shikanime -b backup-before-nix

echo "Home installed."
