{
  imports = [
    ../identities/totalenergies.nix
    ../identities/sfeir.nix
    ../identities/paprec.nix
    ../identities/galec.nix
    ../identities/birdz.nix
    ../profiles/base.nix
    ../profiles/workstation.nix
    ../profiles/xdg.nix
    ../profiles/vcs.nix
    ../profiles/cc.nix
    ../profiles/ruby.nix
    ../profiles/beam.nix
    ../profiles/go.nix
    ../profiles/opam.nix
    ../profiles/rust.nix
    ../profiles/python.nix
    ../profiles/web.nix
    ../profiles/latex.nix
    ../profiles/sql.nix
    ../profiles/cloud.nix
    ../profiles/java.nix
  ];
}
