{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    ../../modules/nixos/base.nix
    ../../modules/nixos/workstation.nix
  ];

  # ── Boot ─────────────────────────────────────────────────────────
  boot = {
    kernelModules = [
      "tcp_bbr"
      "vhost_vsock"
    ];

    kernel.sysctl = {
      "vm.swappiness" = 10;
      "vm.vfs_cache_pressure" = 50;
      "vm.max_map_count" = 524288;

      "fs.inotify.max_user_watches" = 524288;
      "fs.inotify.max_user_instances" = 512;
      "fs.file-max" = 2097152;

      "net.core.default_qdisc" = "fq";
      "net.core.netdev_max_backlog" = 16384;
      "net.core.rmem_default" = 7340032;
      "net.core.rmem_max" = 16777216;
      "net.core.somaxconn" = 65535;
      "net.core.wmem_default" = 7340032;
      "net.core.wmem_max" = 16777216;
      "net.ipv4.ip_local_port_range" = "1024 65535";
      "net.ipv4.tcp_congestion_control" = "bbr";
      "net.ipv4.tcp_fin_timeout" = 30;
      "net.ipv4.tcp_keepalive_time" = 600;
      "net.ipv4.tcp_mtu_probing" = 1;
      "net.ipv4.tcp_rmem" = "4096 87380 16777216";
      "net.ipv4.tcp_wmem" = "4096 65536 16777216";
    };

    # Dual-boot: systemd-boot with manual Windows entry.
    # systemd-boot does NOT auto-detect Windows (unlike GRUB os-prober).
    # The windows."11" entry chainloads the Windows EFI bootloader.
    # ⚠️ Verify efiDeviceHandle with `efibootmgr -v` on the target machine.
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot = {
        enable = true;
        windows."11".efiDeviceHandle = "HD4";
      };
    };
  };

  # ── Filesystems (manual partitioning — dual boot, no disko) ──────
  # Generated by `nixos-generate-config` at install time.
  # Windows partitions must be preserved — do NOT touch NTFS partitions.
  #
  # Example layout (adjust to actual partitioning):
  # /dev/nvme0n1p1  EFI System Partition (shared with Windows)
  # /dev/nvme0n1p2  Windows Recovery
  # /dev/nvme0n1p3  Windows OS (NTFS)
  # /dev/nvme0n1p4  NixOS root (btrfs or ext4)
  # /dev/nvme0n1p5  NixOS swap

  # ── Hardware ─────────────────────────────────────────────────────
  hardware = {
    enableRedistributableFirmware = true;

    nvidia = {
      # RTX 40/50 series — open kernel modules recommended for Turing+
      open = true;

      # Hybrid graphics: NVIDIA Optimus / PRIME offload
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        # ⚠️ Bus IDs must be detected on the actual machine:
        #   lspci -nn | grep -E 'VGA|3D'
        intelBusId = "PCI:0:2:0";
        nvidiaBusId = "PCI:1:0:0";
      };

      # Power management for suspend/resume reliability
      powerManagement = {
        enable = true;
        finegrained = true;
      };
    };

    nvidia-container-toolkit = {
      enable = true;
      mount-nvidia-executables = false;
    };

    graphics = {
      enable = true;
      enable32Bit = true;
    };

    bluetooth.enable = true;
  };

  # OpenRazer for Razer keyboard lighting and laptop peripheral control
  hardware.openrazer = {
    enable = true;
    users = [ "shika" ];
  };

  # ── Networking ───────────────────────────────────────────────────
  networking = {
    hostName = "ishtar";
    networkmanager.enable = true;
    firewall.enable = true;
  };

  # ── Desktop Environment ──────────────────────────────────────────
  services.xserver = {
    enable = true;
    videoDrivers = [ "nvidia" ];
    desktopManager.gnome.enable = true;
    displayManager.gdm.wayland = true;
  };

  # ── Programs ─────────────────────────────────────────────────────
  programs.nix-ld = {
    enable = true;
    libraries = [
      pkgs.stdenv.cc.cc.lib
      pkgs.zlib
    ];
  };

  environment.systemPackages = with pkgs; [
    docker-credential-helpers
    dunst
    libnotify
    polychromatic
    wl-clipboard
  ];

  # ── Services ─────────────────────────────────────────────────────
  services = {
    openssh = {
      enable = true;
      openFirewall = true;
    };

    tailscale = {
      enable = true;
      openFirewall = true;
      authKeyFile = config.sops.secrets.tailscale-authkey.path;
      extraUpFlags = [
        "--accept-routes"
        "--ssh"
      ];
    };

    fwupd.enable = true;
  };

  # ── Virtualisation ───────────────────────────────────────────────
  virtualisation.docker = {
    autoPrune.enable = true;
    rootless = {
      enable = true;
      setSocketVariable = true;
      daemon.settings.features.cdi = true;
    };
  };

  # ── Users ────────────────────────────────────────────────────────
  users.users.shika = {
    extraGroups = [ "wheel" "openrazer" "docker" "networkmanager" ];
    isNormalUser = true;
    home = "/home/shika";
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH+tp1Xfz7NomHCZuDPlfj3XW5hm9t0TiCyEeudRraoe"
    ];
  };

  home-manager.users.shika.imports = [
    ./users/shika/home-configuration.nix
  ];

  # ── Secrets (sops-nix) ───────────────────────────────────────────
  sops = {
    age = {
      generateKey = true;
      keyFile = "/var/lib/sops-nix/key.txt";
      sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    };
    defaultSopsFile = ../../secrets/ishtar.enc.yaml;
    defaultSopsFormat = "yaml";
    secrets = {
      tailscale-authkey = { };
      nix-access-token = { };
    };
    templates.nix-config.content = ''
      extra-access-tokens = "github.com=${config.sops.placeholder.nix-access-token}";
    '';
  };

  nix.extraOptions = ''
    !include ${config.sops.templates.nix-config.path}
  '';
}
