module "tfc_google_sa" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/iam-service-account"
  project_id = module.google_project.project_id
  name       = "terraform-cloud"

  iam = {
    # We allow only tokens generated by a specific TFC workspace impersonation of the service account,
    # that way one identity pool can be used for a TFC Organization, but every workspace will be able to impersonate only a specific SA
    "roles/iam.workloadIdentityUser" = [
      "principalSet://iam.googleapis.com/${google_iam_workload_identity_pool.tfc_pool.name}/attribute.terraform_workspace_id/${tfe_workspace.default["shikanime"].id}"
    ]
  }

  iam_project_roles = {
    "${module.google_project.project_id}" = [
      "roles/browser",
      "roles/iam.securityAdmin",
      "roles/iam.workloadIdentityPoolAdmin",
      "roles/serviceusage.serviceUsageAdmin"
    ]
  }
}
