name: Build Curriculum Vitae
on:
  push:
    paths:
      - pkgs/curriculum-vitae/*
      - flake.nix
      - flake.json
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Prepare Nix environment
        uses: cachix/install-nix-action@v15
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Compile documents
        run: nix build .#curriculumVitae
      - name: Export output path
        run: echo "RELEASE_PATH=$(readlink -f result)" >> "$GITHUB_ENV"
      - name: Export build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Curriculum Vitae
          path: ${{ env.RELEASE_PATH }}
