name: Build Elkia
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Prepare Nix environment
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build image
        run: nix build .#nixosConfigurations.elkia.config.system.build.qcowImage
      - name: Export output path
        run: echo "RELEASE_PATH=$(readlink -f result)" >> "$GITHUB_ENV"
      - name: Export build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Elkia
          path: ${{ env.RELEASE_PATH }}
