name: Check Flake
on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - pkgs/**
      - modules/**
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check Nix Flake
        run: |
          nix flake check \
            --no-build \
            --impure \
            --show-trace
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
