name: Check Flake
on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - pkgs/**
      - modules/**
      - .github/**
  pull_request:
    branches:
      - main
      - gh/*/*/base
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check Nix Flake
        run: |
          nix flake check \
            --no-build \
            --impure \
            --show-trace \
            --all-systems
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
