name: Check Flake
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check Nix Flake
        run: nix flake check --show-trace
