jobs:
  nix:
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/nix.yaml
    with:
      cachix-name: shikanime
  skaffold:
    needs:
      - nix
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/skaffold.yaml
name: Integration
'on':
  pull_request:
    branches:
      - main
      - gh/*/*/base
permissions:
  contents: read
