jobs:
  checks:
    if: ${{ needs['setup-checks'].outputs.continue == 'true' }}
    name: Checks
    needs:
      - setup-checks
    runs-on: ${{ matrix.runner }}
    steps:
      - continue-on-error: true
        id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - continue-on-error: true
        if: ${{ inputs['cachix-name'] != '' }}
        uses: cachix/cachix-action@v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ inputs['cachix-name'] }}
      - run: nix run nixpkgs#direnv allow
      - run: nix run nixpkgs#direnv export gha >> "$GITHUB_ENV"
      - run: nix flake check --accept-flake-config --no-pure-eval --system "${{ matrix.system }}"
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs['setup-checks'].outputs.matrix) }}
  packages:
    if: ${{ needs['setup-packages'].outputs.continue == 'true' }}
    name: Packages
    needs:
      - setup-packages
    runs-on: ${{ matrix.runner }}
    steps:
      - continue-on-error: true
        id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - continue-on-error: true
        if: ${{ inputs['cachix-name'] != '' }}
        uses: cachix/cachix-action@v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ inputs['cachix-name'] }}
      - run: nix build --accept-flake-config --no-pure-eval ".#packages.${{ matrix.system }}.${{ matrix.name }}"
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs['setup-packages'].outputs.matrix) }}
  setup-checks:
    name: Setup Checks
    outputs:
      continue: ${{ steps.setup-checks.outputs.continue }}
      matrix: ${{ steps.setup-checks.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - id: setup-checks
        uses: shikanime-studio/actions/nix/setup-checks@main
  setup-packages:
    name: Setup Packages
    outputs:
      continue: ${{ steps.setup-packages.outputs.continue }}
      matrix: ${{ steps.setup-packages.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - id: setup-packages
        uses: shikanime-studio/actions/nix/setup-packages@main
name: Nix
'on':
  workflow_call:
    inputs:
      cachix-name:
        default: ''
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
      OPERATOR_PRIVATE_KEY:
        required: true
permissions:
  contents: read
