name: Check Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    strategy:
      matrix:
        package:
          - shikanime
          - totalenergies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Init Terraform
        run: terraform -chdir=terraform/${{ matrix.package }} init -backend=false
      - name: Check Terraform
        run: terraform -chdir=terraform/${{ matrix.package }} validate
